### Inital inspection & cleaning

### Objectives:
 * Fetch data from Kaggle then inspect it for cleaning.

In [87]:
import pandas as pd
import numpy as np

In [88]:
df = pd.read_csv('../Data/Raw/transaction_dataset.csv')
df.head()

,Unnamed: 0,Index,Address,FLAG,Avg min between sent tnx,Avg min between received tnx,Time Diff between first and last (Mins),Sent tnx,Received Tnx,Number of Created Contracts,...,ERC20 min val sent,ERC20 max val sent,ERC20 avg val sent,ERC20 min val sent contract,ERC20 max val sent contract,ERC20 avg val sent contract,ERC20 uniq sent token name,ERC20 uniq rec token name,ERC20 most sent token type,ERC20_most_rec_token_type
0,0,1,0x00009277775ac7d0d59eaad8fee3d10ac6c805e8,0,844.26,1093.71,704785.63,721,89,0,...,0.000000,1.683100e+07,271779.920000,0.0,0.0,0.0,39.0,57.0,Cofoundit,Numeraire
1,1,2,0x0002b44ddb1476db43c868bd494422ee4c136fed,0,12709.07,2958.44,1218216.73,94,8,0,...,2.260809,2.260809e+00,2.260809,0.0,0.0,0.0,1.0,7.0,Livepeer Token,Livepeer Token
2,2,3,0x0002bda54cb772d040f779e88eb453cac0daa244,0,246194.54,2434.02,516729.30,2,10,0,...,0.000000,0.000000e+00,0.000000,0.0,0.0,0.0,0.0,8.0,NaN,XENON
3,3,4,0x00038e6ba2fd5c09aedb96697c8d7b8fa6632e5e,0,10219.60,15785.09,397555.90,25,9,0,...,100.000000,9.029231e+03,3804.076893,0.0,0.0,0.0,1.0,11.0,Raiden,XENON
4,4,5,0x00062d1dd1afb6fb02540ddad9cdebfe568e0d89,0,36.61,10707.77,382472.42,4598,20,1,...,0.000000,4.500000e+04,13726.659220,0.0,0.0,0.0,6.0,27.0,StatusNetwork,EOS

### Starting Exploratory Data Analysis (EDA)

Dataset structure using df.info(), df.shape, df.columns, df.dtypes

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9841 entries, 0 to 9840
Data columns (total 51 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   Unnamed: 0                                            9841 non-null   int64
 1   Index                                                 9841 non-null   int64
 2   Address                                               9841 non-null   object
 3   FLAG                                                  9841 non-null   int64
 4   Avg min between sent tnx                              9841 non-null   float64
 5   Avg min between received tnx                          9841 non-null   float64
 6   Time Diff between first and last (Mins)               9841 non-null   float64
 7   Sent tnx                                              9841 non-null   int64
 8   Received Tnx                                          9841 non-null   int64
 9   Number of Created Contracts                           9841 non-null   int64
 10  Unique Received From Addresses                        9841 non-null   int64
 11  Unique Sent To Addresses                              9841 non-null   int64
 12  min value received                                    9841 non-null   float64
 13  max value received                                    9841 non-null   float64
 14  avg val received                                      9841 non-null   float64
 15  min val sent                                          9841 non-null   float64
 16  max val sent                                          9841 non-null   float64
 17  avg val sent                                          9841 non-null   float64
 18  min value sent to contract                            9841 non-null   float64
 19  max val sent to contract                              9841 non-null   float64
 20  avg value sent to contract                            9841 non-null   float64
 21  total transactions (including tnx to create contract  9841 non-null   int64
 22  total Ether sent                                      9841 non-null   float64
 23  total ether received                                  9841 non-null   float64
 24  total ether sent contracts                            9841 non-null   float64
 25  total ether balance                                   9841 non-null   float64
 26   Total ERC20 tnxs                                     9012 non-null   float64
 27   ERC20 total Ether received                           9012 non-null   float64
 28   ERC20 total ether sent                               9012 non-null   float64
 29   ERC20 total Ether sent contract                      9012 non-null   float64
 30   ERC20 uniq sent addr                                 9012 non-null   float64
 31   ERC20 uniq rec addr                                  9012 non-null   float64
 32   ERC20 uniq sent addr.1                               9012 non-null   float64
 33   ERC20 uniq rec contract addr                         9012 non-null   float64
 34   ERC20 avg time between sent tnx                      9012 non-null   float64
 35   ERC20 avg time between rec tnx                       9012 non-null   float64
 36   ERC20 avg time between rec 2 tnx                     9012 non-null   float64
 37   ERC20 avg time between contract tnx                  9012 non-null   float64
 38   ERC20 min val rec                                    9012 non-null   float64
 39   ERC20 max val rec                                    9012 non-null   float64
 40   ERC20 avg val rec                                    9012 non-null   float64
 41   ERC20 min val sent                                   9012 non-null   float64
 42   ERC20 max val sent                                   9012 non-null   float64
 43   ERC20 avg val sent                                   9012 non-null   float64
 44   ERC20 min val sent contract                          9012 non-null   float64
 45   ERC20 max val sent contract                          9012 non-null   float64
 46   ERC20 avg val sent contract                          9012 non-null   float64
 47   ERC20 uniq sent token name                           9012 non-null   float64
 48   ERC20 uniq rec token name                            9012 non-null   float64
 49   ERC20 most sent token type                           7144 non-null   object
 50   ERC20_most_rec_token_type                            8970 non-null   object
dtypes: float64(39), int64(9), object(3)
memory usage: 3.8+ MB

In [90]:
df.shape

(9841, 51)

In [91]:
df.columns

Index(['Unnamed: 0', 'Index', 'Address', 'FLAG', 'Avg min between sent tnx',
       'Avg min between received tnx',
       'Time Diff between first and last (Mins)', 'Sent tnx', 'Received Tnx',
       'Number of Created Contracts', 'Unique Received From Addresses',
       'Unique Sent To Addresses', 'min value received', 'max value received ',
       'avg val received', 'min val sent', 'max val sent', 'avg val sent',
       'min value sent to contract', 'max val sent to contract',
       'avg value sent to contract',
       'total transactions (including tnx to create contract',
       'total Ether sent', 'total ether received',
       'total ether sent contracts', 'total ether balance',
       ' Total ERC20 tnxs', ' ERC20 total Ether received',
       ' ERC20 total ether sent', ' ERC20 total Ether sent contract',
       ' ERC20 uniq sent addr', ' ERC20 uniq rec addr',
       ' ERC20 uniq sent addr.1', ' ERC20 uniq rec contract addr',
       ' ERC20 avg time between sent tnx', ' ERC20 avg time between rec tnx',
       ' ERC20 avg time between rec 2 tnx',
       ' ERC20 avg time between contract tnx', ' ERC20 min val rec',
       ' ERC20 max val rec', ' ERC20 avg val rec', ' ERC20 min val sent',
       ' ERC20 max val sent', ' ERC20 avg val sent',
       ' ERC20 min val sent contract', ' ERC20 max val sent contract',
       ' ERC20 avg val sent contract', ' ERC20 uniq sent token name',
       ' ERC20 uniq rec token name', ' ERC20 most sent token type',
       ' ERC20_most_rec_token_type'],
      dtype='object')

Descriptive statistics: df.describe()

In [92]:
df.describe()

,Unnamed: 0,Index,FLAG,Avg min between sent tnx,Avg min between received tnx,Time Diff between first and last (Mins),Sent tnx,Received Tnx,Number of Created Contracts,Unique Received From Addresses,...,ERC20 max val rec,ERC20 avg val rec,ERC20 min val sent,ERC20 max val sent,ERC20 avg val sent,ERC20 min val sent contract,ERC20 max val sent contract,ERC20 avg val sent contract,ERC20 uniq sent token name,ERC20 uniq rec token name
count,9841.000000,9841.000000,9841.000000,9841.000000,9841.000000,9.841000e+03,9841.000000,9841.000000,9841.000000,9841.000000,...,9.012000e+03,9.012000e+03,9.012000e+03,9.012000e+03,9.012000e+03,9012.0,9012.0,9012.0,9012.000000,9012.000000
mean,4920.000000,1815.049893,0.221421,5086.878721,8004.851184,2.183333e+05,115.931714,163.700945,3.729702,30.360939,...,1.252524e+08,4.346203e+06,1.174126e+04,1.303594e+07,6.318389e+06,0.0,0.0,0.0,1.384931,4.826676
std,2840.996333,1222.621830,0.415224,21486.549974,23081.714801,3.229379e+05,757.226361,940.836550,141.445583,298.621112,...,1.053741e+10,2.141192e+08,1.053567e+06,1.179905e+09,5.914764e+08,0.0,0.0,0.0,6.735121,16.678607
min,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000,0.000000
25%,2460.000000,821.000000,0.000000,0.000000,0.000000,3.169300e+02,1.000000,1.000000,0.000000,1.000000,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000,0.000000
50%,4920.000000,1641.000000,0.000000,17.340000,509.770000,4.663703e+04,3.000000,4.000000,0.000000,2.000000,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000,1.000000
75%,7380.000000,2601.000000,0.000000,565.470000,5480.390000,3.040710e+05,11.000000,27.000000,0.000000,5.000000,...,9.900000e+01,2.946467e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000,2.000000
max,9840.000000,4729.000000,1.000000,430287.670000,482175.490000,1.954861e+06,10000.000000,10000.000000,9995.000000,9999.000000,...,1.000000e+12,1.724181e+10,1.000000e+08,1.120000e+11,5.614756e+10,0.0,0.0,0.0,213.000000,737.000000

In [93]:
df.dtypes

Unnamed: 0                                                int64
Index                                                     int64
Address                                                  object
FLAG                                                      int64
Avg min between sent tnx                                float64
Avg min between received tnx                            float64
Time Diff between first and last (Mins)                 float64
Sent tnx                                                  int64
Received Tnx                                              int64
Number of Created Contracts                               int64
Unique Received From Addresses                            int64
Unique Sent To Addresses                                  int64
min value received                                      float64
max value received                                      float64
avg val received                                        float64
min val sent                                            float64
max val sent                                            float64
avg val sent                                            float64
min value sent to contract                              float64
max val sent to contract                                float64
avg value sent to contract                              float64
total transactions (including tnx to create contract      int64
total Ether sent                                        float64
total ether received                                    float64
total ether sent contracts                              float64
total ether balance                                     float64
 Total ERC20 tnxs                                       float64
 ERC20 total Ether received                             float64
 ERC20 total ether sent                                 float64
 ERC20 total Ether sent contract                        float64
 ERC20 uniq sent addr                                   float64
 ERC20 uniq rec addr                                    float64
 ERC20 uniq sent addr.1                                 float64
 ERC20 uniq rec contract addr                           float64
 ERC20 avg time between sent tnx                        float64
 ERC20 avg time between rec tnx                         float64
 ERC20 avg time between rec 2 tnx                       float64
 ERC20 avg time between contract tnx                    float64
 ERC20 min val rec                                      float64
 ERC20 max val rec                                      float64
 ERC20 avg val rec                                      float64
 ERC20 min val sent                                     float64
 ERC20 max val sent                                     float64
 ERC20 avg val sent                                     float64
 ERC20 min val sent contract                            float64
 ERC20 max val sent contract                            float64
 ERC20 avg val sent contract                            float64
 ERC20 uniq sent token name                             float64
 ERC20 uniq rec token name                              float64
 ERC20 most sent token type                              object
 ERC20_most_rec_token_type                               object
dtype: object

Data quality checks: df.isnull().sum(), df.duplicated().sum()

In [94]:
df.isnull().sum()

Unnamed: 0                                                 0
Index                                                      0
Address                                                    0
FLAG                                                       0
Avg min between sent tnx                                   0
Avg min between received tnx                               0
Time Diff between first and last (Mins)                    0
Sent tnx                                                   0
Received Tnx                                               0
Number of Created Contracts                                0
Unique Received From Addresses                             0
Unique Sent To Addresses                                   0
min value received                                         0
max value received                                         0
avg val received                                           0
min val sent                                               0
max val sent                                               0
avg val sent                                               0
min value sent to contract                                 0
max val sent to contract                                   0
avg value sent to contract                                 0
total transactions (including tnx to create contract       0
total Ether sent                                           0
total ether received                                       0
total ether sent contracts                                 0
total ether balance                                        0
 Total ERC20 tnxs                                        829
 ERC20 total Ether received                              829
 ERC20 total ether sent                                  829
 ERC20 total Ether sent contract                         829
 ERC20 uniq sent addr                                    829
 ERC20 uniq rec addr                                     829
 ERC20 uniq sent addr.1                                  829
 ERC20 uniq rec contract addr                            829
 ERC20 avg time between sent tnx                         829
 ERC20 avg time between rec tnx                          829
 ERC20 avg time between rec 2 tnx                        829
 ERC20 avg time between contract tnx                     829
 ERC20 min val rec                                       829
 ERC20 max val rec                                       829
 ERC20 avg val rec                                       829
 ERC20 min val sent                                      829
 ERC20 max val sent                                      829
 ERC20 avg val sent                                      829
 ERC20 min val sent contract                             829
 ERC20 max val sent contract                             829
 ERC20 avg val sent contract                             829
 ERC20 uniq sent token name                              829
 ERC20 uniq rec token name                               829
 ERC20 most sent token type                             2697
 ERC20_most_rec_token_type                               871
dtype: int64

In [95]:
df.duplicated().sum()

np.int64(0)

Checking the ratio of flagged addresses

In [96]:
df['FLAG'].value_counts()

FLAG
0    7662
1    2179
Name: count, dtype: int64

In [97]:
df.nunique()

Unnamed: 0                                              9841
Index                                                   4729
Address                                                 9816
FLAG                                                       2
Avg min between sent tnx                                5013
Avg min between received tnx                            6223
Time Diff between first and last (Mins)                 7810
Sent tnx                                                 641
Received Tnx                                             727
Number of Created Contracts                               20
Unique Received From Addresses                           256
Unique Sent To Addresses                                 258
min value received                                      4589
max value received                                      6302
avg val received                                        6767
min val sent                                            4719
max val sent                                            6647
avg val sent                                            5854
min value sent to contract                                 3
max val sent to contract                                   4
avg value sent to contract                                 4
total transactions (including tnx to create contract     897
total Ether sent                                        5868
total ether received                                    6728
total ether sent contracts                                 4
total ether balance                                     5717
 Total ERC20 tnxs                                        300
 ERC20 total Ether received                             3460
 ERC20 total ether sent                                 1415
 ERC20 total Ether sent contract                          29
 ERC20 uniq sent addr                                    107
 ERC20 uniq rec addr                                     147
 ERC20 uniq sent addr.1                                    4
 ERC20 uniq rec contract addr                            123
 ERC20 avg time between sent tnx                           1
 ERC20 avg time between rec tnx                            1
 ERC20 avg time between rec 2 tnx                          1
 ERC20 avg time between contract tnx                       1
 ERC20 min val rec                                      1276
 ERC20 max val rec                                      2647
 ERC20 avg val rec                                      3380
 ERC20 min val sent                                      476
 ERC20 max val sent                                     1130
 ERC20 avg val sent                                     1309
 ERC20 min val sent contract                               1
 ERC20 max val sent contract                               1
 ERC20 avg val sent contract                               1
 ERC20 uniq sent token name                               70
 ERC20 uniq rec token name                               121
 ERC20 most sent token type                              304
 ERC20_most_rec_token_type                               466
dtype: int64

### Starting the cleaning process

1. Strip whitespace and lower case all column names

In [98]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
df.columns

Index(['unnamed:_0', 'index', 'address', 'flag', 'avg_min_between_sent_tnx',
       'avg_min_between_received_tnx',
       'time_diff_between_first_and_last_(mins)', 'sent_tnx', 'received_tnx',
       'number_of_created_contracts', 'unique_received_from_addresses',
       'unique_sent_to_addresses', 'min_value_received', 'max_value_received',
       'avg_val_received', 'min_val_sent', 'max_val_sent', 'avg_val_sent',
       'min_value_sent_to_contract', 'max_val_sent_to_contract',
       'avg_value_sent_to_contract',
       'total_transactions_(including_tnx_to_create_contract',
       'total_ether_sent', 'total_ether_received',
       'total_ether_sent_contracts', 'total_ether_balance', 'total_erc20_tnxs',
       'erc20_total_ether_received', 'erc20_total_ether_sent',
       'erc20_total_ether_sent_contract', 'erc20_uniq_sent_addr',
       'erc20_uniq_rec_addr', 'erc20_uniq_sent_addr.1',
       'erc20_uniq_rec_contract_addr', 'erc20_avg_time_between_sent_tnx',
       'erc20_avg_time_between_rec_tnx', 'erc20_avg_time_between_rec_2_tnx',
       'erc20_avg_time_between_contract_tnx', 'erc20_min_val_rec',
       'erc20_max_val_rec', 'erc20_avg_val_rec', 'erc20_min_val_sent',
       'erc20_max_val_sent', 'erc20_avg_val_sent',
       'erc20_min_val_sent_contract', 'erc20_max_val_sent_contract',
       'erc20_avg_val_sent_contract', 'erc20_uniq_sent_token_name',
       'erc20_uniq_rec_token_name', 'erc20_most_sent_token_type',
       'erc20_most_rec_token_type'],
      dtype='object')

2. Drop unnecessary columns

In [99]:
df.drop(columns=['unnamed:_0', 'index'], inplace=True)
df.columns

Index(['address', 'flag', 'avg_min_between_sent_tnx',
       'avg_min_between_received_tnx',
       'time_diff_between_first_and_last_(mins)', 'sent_tnx', 'received_tnx',
       'number_of_created_contracts', 'unique_received_from_addresses',
       'unique_sent_to_addresses', 'min_value_received', 'max_value_received',
       'avg_val_received', 'min_val_sent', 'max_val_sent', 'avg_val_sent',
       'min_value_sent_to_contract', 'max_val_sent_to_contract',
       'avg_value_sent_to_contract',
       'total_transactions_(including_tnx_to_create_contract',
       'total_ether_sent', 'total_ether_received',
       'total_ether_sent_contracts', 'total_ether_balance', 'total_erc20_tnxs',
       'erc20_total_ether_received', 'erc20_total_ether_sent',
       'erc20_total_ether_sent_contract', 'erc20_uniq_sent_addr',
       'erc20_uniq_rec_addr', 'erc20_uniq_sent_addr.1',
       'erc20_uniq_rec_contract_addr', 'erc20_avg_time_between_sent_tnx',
       'erc20_avg_time_between_rec_tnx', 'erc20_avg_time_between_rec_2_tnx',
       'erc20_avg_time_between_contract_tnx', 'erc20_min_val_rec',
       'erc20_max_val_rec', 'erc20_avg_val_rec', 'erc20_min_val_sent',
       'erc20_max_val_sent', 'erc20_avg_val_sent',
       'erc20_min_val_sent_contract', 'erc20_max_val_sent_contract',
       'erc20_avg_val_sent_contract', 'erc20_uniq_sent_token_name',
       'erc20_uniq_rec_token_name', 'erc20_most_sent_token_type',
       'erc20_most_rec_token_type'],
      dtype='object')

Checking if the two columns ('erc20_uniq_sent_addr' and 'erc20_uniq_sent_addr.1') are identical.

In [100]:
(df['erc20_uniq_sent_addr'] == df['erc20_uniq_sent_addr.1']).all()

np.False_

Checking how much they differ.

In [101]:
diff_count = (df['erc20_uniq_sent_addr'] != df['erc20_uniq_sent_addr.1']).sum()
print(f"Number of rows where values differ: {diff_count}")

Number of rows where values differ: 2402

Checking the values in both columns where the value is different.

In [102]:
df_diff = df[df['erc20_uniq_sent_addr'] != df['erc20_uniq_sent_addr.1']]
df_diff[['erc20_uniq_sent_addr', 'erc20_uniq_sent_addr.1']].head(10)

    erc20_uniq_sent_addr  erc20_uniq_sent_addr.1
0                   30.0                     0.0
1                    1.0                     0.0
3                    2.0                     0.0
4                    4.0                     0.0
14                   4.0                     0.0
15                   3.0                     0.0
17                   4.0                     0.0
23                   1.0                     0.0
29                  12.0                     0.0
33                   1.0                     0.0

Since the result shows zeros only, checking the unique values in column 'erc20_uniq_sent_addr.1'.

In [103]:
df['erc20_uniq_sent_addr.1'].unique()

array([ 0.,  1.,  3.,  2., nan])

Visually assessing whether the two columns match, differ, or conflict.

In [104]:
mask = (df['erc20_uniq_sent_addr.1'] != 0) & (df['erc20_uniq_sent_addr.1'].notna())
df.loc[mask, ['erc20_uniq_sent_addr', 'erc20_uniq_sent_addr.1']].head(10)

      erc20_uniq_sent_addr  erc20_uniq_sent_addr.1
378                    1.0                     1.0
472                    0.0                     1.0
566                    1.0                     1.0
1056                   1.0                     1.0
1057                   0.0                     1.0
1427                   1.0                     1.0
2272                   0.0                     1.0
2552                   2.0                     3.0
2768                   1.0                     1.0
3577                   0.0                     1.0

Renaming the column 'erc20_uniq_sent_addr.1' for clarity as it has unique values

In [105]:
df = df.rename(columns={'erc20_uniq_sent_addr.1': 'erc20_uniq_sent_addr_alt'})

Since these columns ('ERC20_uniq_sent_token_name' and 'ERC20_uniq_rec_token_name') are showing as float and not string, checking if those float columns contain actual token names or just NaNs and numbers.

In [106]:
print(df['erc20_uniq_sent_token_name'].dropna().unique()[:10])
print(df['erc20_uniq_rec_token_name'].dropna().unique()[:10])

[39.  1.  0.  6.  4.  3. 11.  2. 25.  7.]
[57.  7.  8. 11. 27.  0.  1.  2. 26. 15.]

Since I got numberical values back, likely the column name is misleading, therefore, going to fill the missing values and then rename the columns.

In [107]:
df['erc20_uniq_sent_token_name'] = df['erc20_uniq_sent_token_name'].fillna(0).astype(int)
df['erc20_uniq_rec_token_name'] = df['erc20_uniq_rec_token_name'].fillna(0).astype(int)

For token type columns (erc20_most_sent_token_type, erc20_most_rec_token_type) filling missing value with a placeholder string like 'No_Token' or 'None':

In [108]:
df['erc20_most_sen_toke_type'] = df['erc20_most_sent_token_type'].fillna('No_Token')
df['erc20_most_rec_token_type'] = df['erc20_most_rec_token_type'].fillna('No_Token')

In [109]:
df.rename(columns={
    'erc20_uniq_sent_token_name': 'erc20_uniq_sent_token_count',
    'erc20_uniq_rec_token_name': 'erc20_uniq_rec_token_count'}, inplace=True)